/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OpUsuario;

import Cliente.AgregarC;
import Cliente.DatosCom;
import Cliente.DatosTarj;
import DatosDely.Departamentos;
import DatosDely.Municipios;
import DatosDely.PrecioReg;
import DatosDely.Precios;
import Kioscos.GKioscos;
import OpAdmin.Reporte;
import Reportes.CotizacionHTML;
import Reportes.Guia;
import Reportes.ListaCompras;
import Usuarios.ListaUsuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class op3 extends javax.swing.JPanel {
private ListaUsuarios listaAgregados;
    private AgregarC facturacion;
    private AgregarC ntarjeta;
    private GKioscos NuKiosco;
    private PrecioReg mun;
    private PrecioReg dep;
    private PrecioReg reg;
    private ListaCompras com;
    /**
     * Creates new form op3
     */
    public op3() {
        initComponents();
    }
        
    public void RecibirRegistros(ListaUsuarios listaAgregados, AgregarC facturacion, AgregarC ntarjeta, GKioscos NuKiosco, PrecioReg mun, PrecioReg depa, PrecioReg reg, Reporte rep, ListaCompras com){
    this.listaAgregados = listaAgregados;
    this.facturacion = facturacion;
    this.ntarjeta = ntarjeta;
    this.mun = mun;
    this.dep = depa;
    this.reg = reg;
    this.com = com;
    ComboFac();
    ComboTarj();
    ComboDepO();
    ComboMunO();
    ComboDepD();
    ComboMunD();
    
    }
    
    public void ComboFac (){
        jComboBox5.removeAllItems();
        int cnit = facturacion.CElementosF();
        DatosCom datos;
        for (int i = 0; i < cnit; i++) {
            datos = facturacion.NoElem(i);
            jComboBox5.addItem(datos.getNomFac());
        }                
    }
    
    public void ComboDepO (){
        jComboBox2.removeAllItems();
        int cdep = dep.CElementosD();
        Departamentos datos;
        for (int i = 0; i < cdep; i++) {
            datos = dep.NoDep(i);
            jComboBox2.addItem(datos.getNombreD());
        }                
    }
    
    public void ComboDepD (){
        jComboBox3.removeAllItems();
        int cdep = dep.CElementosD();
        Departamentos datos;
        for (int i = 0; i < cdep; i++) {
            datos = dep.NoDep(i);
            jComboBox3.addItem(datos.getNombreD());
        }                
    }
    
    public void ComboMunO (){
        jComboBox1.removeAllItems();
        int cmun = mun.CelementosM();
        Municipios datos;
        for (int i = 0; i < cmun; i++) {
            datos = mun.NoMun(i);
            jComboBox1.addItem(datos.getNombreM());
        }                
    }
    
    
    
    
    public void ComboMunD (){
        jComboBox4.removeAllItems();
        int cmun = mun.CelementosM();
        Municipios datos;
        for (int i = 0; i < cmun; i++) {
            datos = mun.NoMun(i);
            jComboBox4.addItem(datos.getNombreM());
        }                
    }
    
    public void ComboTarj (){
        jComboBox6.removeAllItems();
        int ctar = ntarjeta.CelementosT();
        DatosTarj datos;
        for (int i = 0; i < ctar; i++) {
            datos = ntarjeta.NoTarj(i);
            jComboBox6.addItem(datos.getNomTarj());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotones = new javax.swing.ButtonGroup();
        OpcionPago = new javax.swing.ButtonGroup();
        GrupoPrecios = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(970, 620));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(970, 620));
        jPanel1.setMinimumSize(new java.awt.Dimension(970, 620));

        jPanel2.setBackground(new java.awt.Color(73, 68, 68));

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Forma de Pago");

        jRadioButton4.setBackground(new java.awt.Color(73, 68, 68));
        OpcionPago.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Cobro Contra Entrega");

        jRadioButton5.setBackground(new java.awt.Color(73, 68, 68));
        OpcionPago.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Otro Cobros");

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Datos de Facturacion");

        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Realizar Pago");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cobro adicional de Q 5.00");

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pago con Tarjeta de Credito/Debito");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Descargar Guia");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Descargar Factura");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(73, 68, 68));
        jLabel18.setForeground(new java.awt.Color(73, 68, 68));
        jLabel18.setText("jLabel18");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jRadioButton4))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButton3)
                        .addGap(78, 78, 78)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel18)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(36, 36, 36)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Origen");

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Destino");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Departamento");

        jComboBox1.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Departamento");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Municipio");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Municipio");

        jComboBox2.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jComboBox4.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Numero de Paquetes: ");

        jTextField1.setBackground(new java.awt.Color(0, 51, 102));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("#Cantidad");
        jTextField1.setBorder(null);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tamaño de Paquetes");

        jRadioButton1.setBackground(new java.awt.Color(0, 51, 102));
        GrupoBotones.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Mediano");

        jRadioButton2.setBackground(new java.awt.Color(0, 51, 102));
        GrupoBotones.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Grande");

        jRadioButton3.setBackground(new java.awt.Color(0, 51, 102));
        GrupoBotones.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Pequeño");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cotizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("1-10 lbs");

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("11-50 lbs");

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("51- MAS lbs");

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jRadioButton6.setBackground(new java.awt.Color(0, 51, 102));
        GrupoPrecios.add(jRadioButton6);
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Estandar");

        jRadioButton7.setBackground(new java.awt.Color(0, 51, 102));
        GrupoPrecios.add(jRadioButton7);
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Especial");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jRadioButton6)
                .addGap(112, 112, 112)
                .addComponent(jRadioButton7))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jRadioButton3)
                                    .addGap(71, 71, 71)
                                    .addComponent(jRadioButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(113, 113, 113)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(154, 154, 154)
                                    .addComponent(jButton1)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MousePressed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String preg = jComboBox3.getSelectedItem().toString();
         Precios valor = this.reg.verificar(preg);
         int cant = Integer.parseInt(jTextField1.getText());
         double test;
         double tesp;
         if (jRadioButton3.isSelected()){
         
         test = valor.getPreregular() * cant*15;
         tesp = valor.getPrestandar() * cant * 15;
         jLabel17.setText(String.valueOf(test));
         jLabel16.setText(String.valueOf(tesp));
                 }
         if (jRadioButton1.isSelected()){
                 test = valor.getPreregular() * cant*25;
         tesp = valor.getPrestandar() * cant * 25;
         jLabel17.setText(String.valueOf(test));
         jLabel16.setText(String.valueOf(tesp));
                 }
         
         if (jRadioButton2.isSelected()){
                 test = valor.getPreregular() * cant*35;
         tesp = valor.getPrestandar() * cant * 35;
         jLabel17.setText(String.valueOf(test));
         jLabel16.setText(String.valueOf(tesp));
                 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String dep,muni;
        dep = jComboBox2.getSelectedItem().toString();
        System.out.println(dep);
        mun.municipios(dep);
        System.out.println(mun.municipios(dep));
        
        
        
        jComboBox1.removeAllItems();
        int cmun = mun.CelementosM();
        Municipios datos;
        for (int i = 0; i < cmun; i++) {
            datos = mun.NoMun(i);
            jComboBox1.addItem(datos.getNombreM());
        }                
    
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            String TamPaque,cantidad,departamento,municipio,nombre,Nit,Total,titulo;
            
            
            
               
            
                               // TODO add your handling code here:
        String tot;
        if (jRadioButton6.isSelected()){
        
            if (jRadioButton4.isSelected()){
            tot = String.valueOf(Double.parseDouble(jLabel17.getText()) + 5);
            jLabel18.setText(tot);
            JOptionPane.showMessageDialog(null,"Su compra se ha realizado con exito, el valor fue de: " + tot);
            if (jRadioButton3.isSelected()){
            TamPaque = "Pequeño 1";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
            com.GCR(TamPaque, cantidad, departamento, municipio, nombre, Nit, Total);
                        }
            if (jRadioButton1.isSelected()){
            TamPaque = "Mediano 2";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
                                com.GCR(TamPaque, cantidad, departamento, municipio, nombre, Nit, Total);
                        }
            if (jRadioButton2.isSelected()){
            TamPaque = "Grande 3";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
                                           com.GCR(TamPaque, cantidad, departamento, municipio, nombre, Nit, Total);
                        } 
            } 
            if (jRadioButton5.isSelected()){
            tot = String.valueOf( Double.parseDouble(jLabel17.getText()) + 0);
            jLabel18.setText(tot);
            JOptionPane.showMessageDialog(null,"Su compra se ha realizado con exito, el valor fue de: " + tot);
            if (jRadioButton3.isSelected()){
            TamPaque = "Pequeño 1";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
            com.GCR(TamPaque, cantidad, departamento, municipio, nombre, Nit, Total);
                        }
            if (jRadioButton1.isSelected()){
            TamPaque = "Mediano 2";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
                                com.GCR(TamPaque, cantidad, departamento, municipio, nombre, Nit, Total);
                        }
            if (jRadioButton2.isSelected()){
            TamPaque = "Grande 3";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
                                           com.GCR(TamPaque, cantidad, departamento, municipio, nombre, Nit, Total);
                        } 
            }
        }
        if (jRadioButton7.isSelected()){
        
            if (jRadioButton4.isSelected()){
            tot = String.valueOf(Double.parseDouble(jLabel16.getText()) + 5);
            jLabel18.setText(tot);
            JOptionPane.showMessageDialog(null,"Su compra se ha realizado con exito, el valor fue de: " + tot);
            if (jRadioButton3.isSelected()){
            TamPaque = "Pequeño 1";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
            com.GCR(TamPaque, cantidad, departamento, municipio, nombre, Nit, Total);
                        }
            if (jRadioButton1.isSelected()){
            TamPaque = "Mediano 2";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
                                com.GCR(TamPaque, cantidad, departamento, municipio, nombre, Nit, Total);
                        }
            if (jRadioButton2.isSelected()){
            TamPaque = "Grande 3";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
                                           com.GCR(TamPaque, cantidad, departamento, municipio, nombre, Nit, Total);
                        } 
            } 
            if (jRadioButton5.isSelected()){
            tot = String.valueOf( Double.parseDouble(jLabel16.getText()) + 0);
            jLabel18.setText(tot);
            JOptionPane.showMessageDialog(null,"Su compra se ha realizado con exito, el valor fue de: " + tot);
            if (jRadioButton3.isSelected()){
            TamPaque = "Pequeño 1";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
            com.GCR(TamPaque, cantidad, departamento, municipio, nombre, Nit, Total);
                        }
            if (jRadioButton1.isSelected()){
            TamPaque = "Mediano 2";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
                                com.GCR(TamPaque, cantidad, departamento, municipio, nombre, Nit, Total);
                        }
            if (jRadioButton2.isSelected()){
            TamPaque = "Grande 3";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
                                           com.GCR(TamPaque, cantidad, departamento, municipio, nombre, Nit, Total);
                        } 
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String TamPaque,cantidad,departamento,municipio,nombre,Nit,Total,titulo,codigo;
            
            if (jRadioButton3.isSelected()){
            TamPaque = "Pequeño 1";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
            codigo="IPC1Crs_04";
            
                        CotizacionHTML factura = new CotizacionHTML();
                        factura.CrearDoc(titulo,codigo, nombre, cantidad, TamPaque, departamento, municipio, Nit, Total);
            }
            if (jRadioButton1.isSelected()){
            TamPaque = "Mediano 2";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
            codigo="IPC1Crs_04";
            
            CotizacionHTML factura = new CotizacionHTML();
            
            factura.CrearDoc(titulo,codigo, nombre, cantidad, TamPaque, departamento, municipio, Nit, Total);
            }
            if (jRadioButton2.isSelected()){
            TamPaque = "Grande 3";
            cantidad = jTextField1.getText();
            departamento = jComboBox3.getSelectedItem().toString();
            municipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Reporte";
            Total = jLabel18.getText();
            Nit="123";
            codigo="IPC1Crs_04";
            
            CotizacionHTML factura = new CotizacionHTML();
            
            factura.CrearDoc(titulo,codigo, nombre, cantidad, TamPaque, departamento, municipio, Nit, Total);
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
       
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String TamPaque,cantidad,Odepartamento,Omunicipio,Ddepartamento,Dmunicipio,nombre,Nit,Total,titulo,codigo;
        
         // TODO add your handling code here:
        
                                          
        cantidad = jTextField1.getText();
            Odepartamento = jComboBox2.getSelectedItem().toString();
            Omunicipio = jComboBox1.getSelectedItem().toString();
            Ddepartamento = jComboBox3.getSelectedItem().toString();
            Dmunicipio = jComboBox4.getSelectedItem().toString();
            nombre = jComboBox5.getSelectedItem().toString();
            titulo = "Guia";
            Total = jLabel18.getText();
            Nit="123";
            codigo="IPC1Crs_04";
           
            Guia guias = new Guia();
            
            guias.CrearDoc(titulo, codigo, nombre, cantidad, Odepartamento, Omunicipio, Total, Ddepartamento, Dmunicipio);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBotones;
    private javax.swing.ButtonGroup GrupoPrecios;
    private javax.swing.ButtonGroup OpcionPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
