/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OpUsuario;

import Cliente.AgregarC;
import DatosDely.PrecioReg;
import Kioscos.GKioscos;
import OpAdmin.Reporte;
import Reportes.DatosF;
import Reportes.ListaCompras;
import Usuarios.ListaUsuarios;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author rodri
 */
public class op4 extends javax.swing.JPanel {
private ListaUsuarios listaAgregados;
    private AgregarC facturacion;
    private AgregarC ntarjeta;
    private GKioscos NuKiosco;
    private PrecioReg mun;
    private PrecioReg dep;
    private PrecioReg reg;
    DefaultTableModel tven;
    private ListaCompras com;
    /**
     * Creates new form op4
     */
    public op4() {
        initComponents();
    }
    
    public void RecibirRegistros(ListaUsuarios listaAgregados, AgregarC facturacion, AgregarC ntarjeta, GKioscos NuKiosco, PrecioReg mun, PrecioReg depa, PrecioReg reg, Reporte rep, ListaCompras com){
    this.listaAgregados = listaAgregados;
    this.facturacion = facturacion;
    this.ntarjeta = ntarjeta;
    this.mun = mun;
    this.dep = depa;
    this.reg = reg;
    this.com = com;
    llenarTVen();
    }
    
    public void llenarTVen(){
    this.tven = new DefaultTableModel();
    
    tven.addColumn("No.");
    tven.addColumn("Departamento");
    tven.addColumn("Nombre");
    tven.addColumn("Cant Paquetes");
    tven.addColumn("Total");
    
    
    int cantidad = this.com.CCompras();
        int No_ = 0;
    DatosF tmp;
    for (int i = 0; i < cantidad; i++) {
        tmp = this.com.NoCom(i);
            //addRowTable(i, codigo, porc);
            addRowTableD(i,tmp.getDepartamento(),tmp.getNombre(),tmp.getCantidad(),tmp.getTotal());
           
            
        }
    this.Tablarep.setModel(tven);
        this.Tablarep.getColumnModel().getColumn(0).setMaxWidth(30);
    }
    
    private void addRowTableD(int id, String Departamento, String Nombre,String Cant, String Total){
        tven.addRow(new Object[]{String.valueOf(id), Departamento, Nombre,Cant, Total});
        this.Tablarep.setModel(tven);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablarep = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(970, 620));

        Tablarep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(Tablarep);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablarep;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
