/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OpAdmin;

import Cliente.AgregarC;
import DatosDely.PrecioReg;
import DatosDely.Precios;
import Kioscos.GKioscos;
import Reportes.ListaCompras;
import Usuarios.ListaUsuarios;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodri
 */
public class MPrecios extends javax.swing.JPanel {
private ListaUsuarios listaAgregados;
    private AgregarC facturacion;
    private AgregarC ntarjeta;
    private GKioscos NuKiosco;
    private PrecioReg mun;
    private PrecioReg depa;
    private PrecioReg reg;
    DefaultTableModel tdeps;
    /**
     * Creates new form MPrecios
     */
    public MPrecios() {
        initComponents();
    }

    public void RecibirRegistros(ListaUsuarios listaAgregados, AgregarC facturacion, GKioscos NuKiosco, AgregarC ntarjeta, PrecioReg mun, PrecioReg dep, PrecioReg reg, ListaCompras com){
    this.listaAgregados = listaAgregados;
    this.facturacion = facturacion;
    this.NuKiosco = NuKiosco;
    this.ntarjeta = ntarjeta;
    this.depa = dep;
    this.mun = mun;
    this.reg = reg;
    ComboReg();
    llenarTReg();
    }
    
    public void ComboReg(){
        jComboBox1.removeAllItems();
        int cdep = reg.Cantidad();
        Precios datos;
        for (int i = 0; i < cdep; i++) {
            datos = reg.Obtener(i);
            jComboBox1.addItem(datos.getCodigo());
        }                
    }
    
    public void llenarTReg(){
    this.tdeps = new DefaultTableModel();
    tdeps.addColumn("No.");
    tdeps.addColumn("Cod Region");
    tdeps.addColumn("Nom Region");
    tdeps.addColumn("Pre Estandar");
    tdeps.addColumn("Pre Especial");
    
    int cantidad = this.reg.Cantidad();
        int No_ = 0;
    Precios tmp;
    for (int i = 0; i < cantidad; i++) {
            tmp = this.reg.Obtener(i);
            //addRowTable(i, codigo, porc);
            addRowTable(i,tmp.getCodigo(),tmp.getNombre(),tmp.getPrestandar(),tmp.getPreregular());
           
            
        }
    this.tablareg.setModel(tdeps);
        this.tablareg.getColumnModel().getColumn(0).setMaxWidth(30);
    }
    
    private void addRowTable(int id, String codigo, String nombre, double pestandar,double pespecial){
        tdeps.addRow(new Object[]{String.valueOf(id), codigo, nombre,String.valueOf(pestandar),String.valueOf(pespecial)});
        this.tablareg.setModel(tdeps);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablareg = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 360));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 51, 102));

        tablareg.setBackground(new java.awt.Color(51, 51, 51));
        tablareg.setForeground(new java.awt.Color(255, 255, 255));
        tablareg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(tablareg);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 100, 380, 120));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manejo de Precios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nuevo Precio Especial");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo de la Region");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nuevo Precio Estandar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 110, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 90, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 90, -1));

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precios por Region");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String reg = jComboBox1.getSelectedItem().toString();
        String pest = jTextField2.getText();
        String pesp = jTextField1.getText();
        double cest = 0;
        double cesp = 0;
        System.out.println(reg);
        if (pest != null){
            if (!pest.equals("")){
                cest = Double.parseDouble(pest);
            }
        }
        
        if (pesp != null){
            if (!pesp.equals("")){
                cesp = Double.parseDouble(pesp);
            }
        }
        
        this.reg.actualizar(reg, cest, cesp);
        llenarTReg();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tablareg;
    // End of variables declaration//GEN-END:variables
}
